excluded:
  - Pods
  - docs
  - build
  - scripts

disabled_rules:
  # metrics
  - nesting

  # lint
  - notification_center_detachment
  - weak_delegate

  # idiomatic
  - force_cast
  - type_name

  # style
  - identifier_name

opt_in_rules:
  # performance
  - empty_count
  - first_where
  - sorted_first_last
  - contains_over_first_not_nil
  - last_where

  # idiomatic
  - fatal_error_message
  - xctfail_message
  - discouraged_object_literal
  - discouraged_optional_boolean
  # - discouraged_optional_collection
  - for_where
  - function_default_parameter_at_end
  - legacy_random
  - no_extension_access_modifier
  - redundant_type_annotation
  - static_operator
  - toggle_bool
  - unavailable_function

  # style
  - attributes
  - number_separator
  - operator_usage_whitespace
  - sorted_imports
  - vertical_parameter_alignment_on_call
  - void_return
  - closure_spacing
  - empty_enum_arguments
  - implicit_return
  - modifier_order
  - multiline_arguments
  - multiline_parameters
  - trailing_closure
  - unneeded_parentheses_in_closure_argument
  - vertical_whitespace_between_cases

  # lint
  - overridden_super_call
  - yoda_condition
  - weak_computed_property
  - anyobject_protocol
  - array_init
  - empty_xctest_method
  - identical_operands
  - prohibited_super_call
  - unused_import
  - unused_private_declaration

line_length: 200
file_length: 600

type_body_length: 500

function_body_length: 250

cyclomatic_complexity: 15
